name: migrant_db_sqlite
version: 0.0.1
description: SQLite gateway for Migrant
homepage: "https://github.com/f3ath/migrant-db-sqlite"

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  migrant: ^0.0.7
  sqflite_common: ^2.2.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  check_coverage: ^0.0.4
  cider: ^0.1.0
  sqflite_common_ffi: ^2.1.1
  path: ^1.8.1

cider:
  link_template:
    tag: https://github.com/f3ath/migrant-db-sqlite/releases/tag/%tag%
    diff: https://github.com/f3ath/migrant-db-sqlite/compare/%from%...%to%