name: migrant_db_sqlite
version: 0.0.2
description: SQLite gateway for Migrant. Allows performing database schema migrations in SQLite databases.
homepage: "https://github.com/f3ath/migrant-db-sqlite"

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  migrant: ^0.0.9
  sqflite_common: ^2.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.20.1
  check_coverage: ^0.0.4
  cider: ^0.2.7
  sqflite_common_ffi: ^2.1.1
  path: ^1.8.1

cider:
  link_template:
    tag: https://github.com/f3ath/migrant-db-sqlite/releases/tag/%tag%
    diff: https://github.com/f3ath/migrant-db-sqlite/compare/%from%...%to%